"""Added initial table

Revision ID: 04cee7e37e51
Revises: 08276cad4042
Create Date: 2023-07-28 16:06:55.900560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04cee7e37e51'
down_revision = '08276cad4042'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
