"""Added initial table

Revision ID: 08276cad4042
Revises: 469d8535e70a
Create Date: 2023-07-28 16:04:11.060443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08276cad4042'
down_revision = ''
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
